//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class All_Employees_View
    {
        public int Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Position_Id { get; set; }
        public string Employee_Fname { get; set; }
        public string Employee_Lname { get; set; }
        public string Password { get; set; }
        public string Privileges_Num { get; set; }
        public Nullable<int> Status { get; set; }
        public string Birth_Date { get; set; }
    }
}
