//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualLeaves
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnnualLeaves()
        {
            this.LeavesDayChanges = new HashSet<LeavesDayChanges>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> AnnualSum { get; set; }
        public Nullable<byte> Available { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> LeaveType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeavesDayChanges> LeavesDayChanges { get; set; }
        public virtual HR_Employee_Contract HR_Employee_Contract { get; set; }
    }
}
