//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnnualLeavesContractsView
    {
        public int AnnualLeavesId { get; set; }
        public int Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<byte> Description { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> ContractStatus { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<byte> AnnualSum { get; set; }
        public Nullable<byte> Available { get; set; }
        public Nullable<byte> Status { get; set; }
        public Nullable<int> LeaveType { get; set; }
    }
}
