//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Template_Details
    {
        public int Id { get; set; }
        public Nullable<int> Template_Id { get; set; }
        public string Day { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual Contract_Templates Contract_Templates { get; set; }
    }
}
