//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daysoff
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Desc { get; set; }
        public int Status { get; set; }
    }
}
