//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Contracts
    {
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public string Employee_Fname { get; set; }
        public string Employee_Lname { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Employee_Status { get; set; }
        public int Id { get; set; }
        public Nullable<decimal> Daily_Working_Hours { get; set; }
        public Nullable<byte> Description { get; set; }
        public Nullable<int> Contract_Status { get; set; }
        public Nullable<int> Role { get; set; }
    }
}
