//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_Employee()
        {
            this.LeavesRequests = new HashSet<LeavesRequests>();
            this.Attributes_Values = new HashSet<Attributes_Values>();
            this.LeavesRequestsResponse = new HashSet<LeavesRequestsResponse>();
            this.HR_Employee_Contract = new HashSet<HR_Employee_Contract>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Department_Id { get; set; }
        public Nullable<int> Position_Id { get; set; }
        public string Employee_Fname { get; set; }
        public string Employee_Lname { get; set; }
        public string Password { get; set; }
        public string Privileges_Num { get; set; }
        public Nullable<int> Status { get; set; }
        public string Personal_Email { get; set; }
        public string Home_Address { get; set; }
        public string Personal_Mobile_Number { get; set; }
        public string Birth_Date { get; set; }
        public string Transportation { get; set; }
    
        public virtual HR_Department HR_Department { get; set; }
        public virtual HR_Position HR_Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeavesRequests> LeavesRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attributes_Values> Attributes_Values { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeavesRequestsResponse> LeavesRequestsResponse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HR_Employee_Contract> HR_Employee_Contract { get; set; }
    }
}
