//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_Employee_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_Employee_Contract()
        {
            this.AnnualLeaves = new HashSet<AnnualLeaves>();
            this.Contract_Details = new HashSet<Contract_Details>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<byte> Description { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<decimal> Daily_Working_Hours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnnualLeaves> AnnualLeaves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Details> Contract_Details { get; set; }
        public virtual HR_Employee HR_Employee { get; set; }
        public virtual HR_Position HR_Position { get; set; }
    }
}
