//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeavesDayChanges
    {
        public int Id { get; set; }
        public Nullable<int> AnnualLeavesID { get; set; }
        public Nullable<int> LeavesRequestID { get; set; }
        public Nullable<byte> AmountRemoved { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual AnnualLeaves AnnualLeaves { get; set; }
        public virtual LeavesRequests LeavesRequests { get; set; }
    }
}
