//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationUnipi.Models.MyApplicationUnipi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyApplicationUnipiEntities : DbContext
    {
        public MyApplicationUnipiEntities()
            : base("name=MyApplicationUnipiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnnualLeaves> AnnualLeaves { get; set; }
        public virtual DbSet<Contract_Templates> Contract_Templates { get; set; }
        public virtual DbSet<Daysoff> Daysoff { get; set; }
        public virtual DbSet<HR_Department> HR_Department { get; set; }
        public virtual DbSet<HR_Position> HR_Position { get; set; }
        public virtual DbSet<LeavesDayChanges> LeavesDayChanges { get; set; }
        public virtual DbSet<LeavesRequests> LeavesRequests { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<LeaveRequestsFiles> LeaveRequestsFiles { get; set; }
        public virtual DbSet<HR_Employee> HR_Employee { get; set; }
        public virtual DbSet<All_Employees_View> All_Employees_View { get; set; }
        public virtual DbSet<AnnualLeavesContractsView> AnnualLeavesContractsView { get; set; }
        public virtual DbSet<Employee_Contracts> Employee_Contracts { get; set; }
        public virtual DbSet<Attributes> Attributes { get; set; }
        public virtual DbSet<Attributes_Values> Attributes_Values { get; set; }
        public virtual DbSet<LeavesRequestsResponse> LeavesRequestsResponse { get; set; }
        public virtual DbSet<Employee_Details> Employee_Details { get; set; }
        public virtual DbSet<Contract_Details> Contract_Details { get; set; }
        public virtual DbSet<Contract_Template_Details> Contract_Template_Details { get; set; }
        public virtual DbSet<HR_Employee_Contract> HR_Employee_Contract { get; set; }
    }
}
